### ISSUE TITLE
Objective-C/Swift Framework API for Tangram-ES

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#1027]
This issue will show Tangram-ES API progress of exposed functionalities through the tangram framework for Objective-C and Swift bindings.
- [x] Queue scene updates (#851)
- [x] Screen coords to lat/lon conversions (#859)
- [x] Delegate for event `onSceneLoaded`
- [x] Delegate for event `onMapReady` (#856)
- [x] Delegate for event `onFeatureSelected` (#855)
- [x] ~~Dynamic API Key update~~ (Should be done at SDK level) (#853)
- [x] Dynamic style replacement (#852)
- [x] Marker API
- [x] System fonts (#825)

cc @msmollin, @ecgreb
